[package]
name = "bevy_prototype_debug_lines"
version = "0.3.3"
authors = ["Michael Palmos <toqoz@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "A prototype plugin providing a simple line drawing API for bevy."
homepage = "https://github.com/Toqozz/bevy_debug_lines"
repository = "https://github.com/Toqozz/bevy_debug_lines"
keywords = ["debug", "line", "graphics", "bevy", "drawing"]
categories = ["game-engines", "rendering", "game-development"]

exclude = [
    "demo.gif",
    "demo_2.png",
    "demo_2.webm",
]

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"] }

[features]
example_deps = ["bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11"]

[[example]]
name = "3d"
required-features = ["example_deps"]

[[example]]
name = "2d"
required-features = ["example_deps"]

[[example]]
name = "bench"
required-features = ["example_deps"]

[[example]]
name = "user_lines"
required-features = ["example_deps"]

[[example]]
name = "depth_test"
required-features = ["example_deps"]

[[example]]
name = "movement"
required-features = ["example_deps"]
